[env:firebeetle2_esp32e]
platform = espressif32
board = dfrobot_firebeetle2_esp32e
framework = arduino

; --- SERIAL SETTINGS ---
monitor_speed = 115200
upload_speed = 921600

; --- OTA SETTINGS ---
; When you are ready to go wireless, uncomment the line below and add your ESP's IP
; upload_protocol = espota
; upload_port = 192.168.1.XXX 

; --- LIBRARIES ---
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.5