#include "display/display.h"
#include "config.h"
#include "joystick/joystick.h"
#include "attack/attack.h"
#include "attack/sniffer.h"
#include "ui/menu.h"
#include <SPI.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>
#include <WiFi.h>
#include <time.h>

// Grid layout constants
#define HEADER_H   12
#define GRID_COLS  2
#define GRID_ROWS  2
#define CELL_W     64                        // 128 / 2
#define CELL_H     26                        // (64 - 12) / 2
#define GRID_START (HEADER_H)

// Menu items
struct MenuItem {
    const char* label;
    const char* icon; // Simple text icon, replace with bitmap later
};

static const MenuItem menuItems[MENU_ITEM_COUNT] = {
    { "WiFi" },
    { "Settings"},
    { "Info"}
};

const unsigned char myLogo[] PROGMEM = {
    0x00, 0x00 // Replace with your generated bytes from image2cpp
};

static Adafruit_SSD1306 display(128, 64, &SPI, OLED_DC, OLED_RESET, OLED_CS);

void initDisplay() {
    SPI.begin(18, 19, 23, OLED_CS);

    if (!display.begin(SSD1306_SWITCHCAPVCC)) {
        Serial.println("SSD1306 failed");
        for(;;);
    }

    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
}

void showLogo() {
    display.clearDisplay();
    display.drawBitmap(0, 0, myLogo, 128, 64, SSD1306_WHITE);
    display.display();
    delay(2000);
}

void drawWiFiIcon(int x, int y, int strength) {
    display.fillCircle(x, y, 1, SSD1306_WHITE);

    if (strength >= 1) {
        display.drawPixel(x-1, y-1, SSD1306_WHITE);
        display.drawPixel(x+1, y-1, SSD1306_WHITE);
        display.drawPixel(x-2, y-2, SSD1306_WHITE);
        display.drawPixel(x+2, y-2, SSD1306_WHITE);
    }
    if (strength >= 2) {
        display.drawPixel(x-2, y-3, SSD1306_WHITE);
        display.drawPixel(x+2, y-3, SSD1306_WHITE);
        display.drawPixel(x-3, y-4, SSD1306_WHITE);
        display.drawPixel(x+3, y-4, SSD1306_WHITE);
        display.drawPixel(x-4, y-5, SSD1306_WHITE);
        display.drawPixel(x+4, y-5, SSD1306_WHITE);
    }
    if (strength >= 3) {
        display.drawPixel(x-4, y-6, SSD1306_WHITE);
        display.drawPixel(x+4, y-6, SSD1306_WHITE);
        display.drawPixel(x-5, y-7, SSD1306_WHITE);
        display.drawPixel(x+5, y-7, SSD1306_WHITE);
        display.drawPixel(x-6, y-8, SSD1306_WHITE);
        display.drawPixel(x+6, y-8, SSD1306_WHITE);
    }
    if (strength >= 4) {
        display.drawPixel(x-6, y-9,  SSD1306_WHITE);
        display.drawPixel(x+6, y-9,  SSD1306_WHITE);
        display.drawPixel(x-7, y-10, SSD1306_WHITE);
        display.drawPixel(x+7, y-10, SSD1306_WHITE);
        display.drawPixel(x-8, y-11, SSD1306_WHITE);
        display.drawPixel(x+8, y-11, SSD1306_WHITE);
    }
}

void drawGridCell(int index, int selected) {
    int col = index % GRID_COLS;
    int row = index / GRID_COLS;

    int x = col * CELL_W;
    int y = GRID_START + (row * CELL_H);

    bool isSelected = (index == selected);

    // Draw cell background
    if (isSelected) {
        display.fillRect(x, y, CELL_W, CELL_H, SSD1306_WHITE);
        display.setTextColor(SSD1306_BLACK);
    } else {
        display.drawRect(x, y, CELL_W, CELL_H, SSD1306_WHITE);
        display.setTextColor(SSD1306_WHITE);
    }

    // Draw icon (centered horizontally, upper portion of cell)
    display.setTextSize(1);
    display.setCursor(x + (CELL_W / 2) - 3, y + 6);
    display.print(menuItems[index].icon);

    // Draw label (centered horizontally, lower portion of cell)
    int labelLen = strlen(menuItems[index].label) * 6; // 6px per char at textsize 1
    display.setCursor(x + (CELL_W / 2) - (labelLen / 2), y + 16);
    display.print(menuItems[index].label);

    // Reset text color
    display.setTextColor(SSD1306_WHITE);
}

void drawHomeMenu() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);

    // Header line with status info
    display.drawFastHLine(0, HEADER_H, 128, SSD1306_WHITE);

    // WiFi indicator
    if (WiFi.status() == WL_CONNECTED) {
        int rssi = WiFi.RSSI();
        int strength;
        if (rssi >= -50)      strength = 4;
        else if (rssi >= -60) strength = 3;
        else if (rssi >= -70) strength = 2;
        else                  strength = 1;
        drawWiFiIcon(10, 10, strength);
    } else {
        display.setCursor(6, 2);
        display.print("X");
    }

    // Time
    display.setCursor(50, 2);
    time_t now = time(nullptr);
    if (now > 1577836800) {
        struct tm* timeinfo = localtime(&now);
        char time_str[6];
        strftime(time_str, sizeof(time_str), "%H:%M", timeinfo);
        display.print(time_str);
    } else {
        display.print("--:--");
    }

    // Battery
    display.setCursor(95, 2);
    display.print("100%");

    // Main menu items
    const char* mainItems[] = {
        "WiFi Tools",
        "Settings",
        "Device Info"
    };
    
    // Draw main menu items with selection
    HomeMenuItem selected = getCurrentHomeItem();
    for (int i = 0; i < HOME_SUBMENU_COUNT; i++) {
        display.setCursor(5, 20 + (i * 12));
        
        if (i == selected) {
            display.print(">> ");
            display.setTextColor(SSD1306_BLACK);
            display.print(mainItems[i]);
            display.setTextColor(SSD1306_WHITE);
            display.println();
        } else {
            display.print("   ");
            display.println(mainItems[i]);
        }
    }

    display.display();
}

void drawScanResults() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[SCAN RESULTS]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    display.setCursor(0, 15);
    display.println("Scanning networks...");
    display.println("Press back to exit");
    
    display.display();
}

void drawWiFiSubmenu() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[WiFi TOOLS]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    // WiFi submenu items
    const char* wifiItems[] = {
        "Scan Networks",
        "Deauth Attack",
        "Beacon Spoof",
        "Packet Stats",
        "EXIT"
    };
    
    // Draw submenu items with selection
    int selected = getCurrentWiFiItem();
    for (int i = 0; i < WIFI_SUBMENU_COUNT; i++) {
        display.setCursor(5, 15 + (i * 9));
        
        if (i == selected) {
            display.print(">> ");
            display.setTextColor(SSD1306_BLACK);
            display.print(wifiItems[i]);
            display.setTextColor(SSD1306_WHITE);
            display.println();
        } else {
            display.print("   ");
            display.println(wifiItems[i]);
        }
    }
    
    display.display();
}

void drawSettingsMenu() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[SETTINGS]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    // Settings submenu items
    const char* settingsItems[] = {
        "Channel: Auto",
        "Power: Max",
        "Brightness: High",
        "EXIT"
    };
    
    // Draw submenu items with selection
    int selected = getCurrentSettingsItem();
    for (int i = 0; i < SETTINGS_SUBMENU_COUNT; i++) {
        display.setCursor(5, 15 + (i * 9));
        
        if (i == selected) {
            display.print(">> ");
            display.setTextColor(SSD1306_BLACK);
            display.print(settingsItems[i]);
            display.setTextColor(SSD1306_WHITE);
            display.println();
        } else {
            display.print("   ");
            display.println(settingsItems[i]);
        }
    }
    
    display.display();
}

void drawInfoMenu() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[DEVICE INFO]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    // Info submenu items
    const char* infoItems[] = {
        "Device: ESP32",
        "Status: Ready",
        "EXIT"
    };
    
    // Draw submenu items with selection
    int selected = getCurrentInfoItem();
    for (int i = 0; i < INFO_SUBMENU_COUNT; i++) {
        display.setCursor(5, 15 + (i * 9));
        
        if (i == selected) {
            display.print(">> ");
            display.setTextColor(SSD1306_BLACK);
            display.print(infoItems[i]);
            display.setTextColor(SSD1306_WHITE);
            display.println();
        } else {
            display.print("   ");
            display.println(infoItems[i]);
        }
    }
    
    display.display();
}

void drawDeauthStatus() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[DEAUTH ATTACK]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    // Status
    AttackState state = getDeauthState();
    display.setCursor(0, 15);
    
    if (state == ATTACK_STATE_RUNNING) {
        display.println("Status: ACTIVE");
        display.println("Packets: " + String(getDeauthPacketsCount()));
        display.println("");
        display.println("Press to stop");
    } else if (state == ATTACK_STATE_PAUSED) {
        display.println("Status: PAUSED");
    } else {
        display.println("Status: IDLE");
        display.println("Select target to attack");
    }
    
    display.display();
}

void drawBeaconStatus() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[BEACON SPOOF]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    // Status
    AttackState state = getBeaconState();
    display.setCursor(0, 15);
    
    if (state == ATTACK_STATE_RUNNING) {
        display.println("Status: SPOOFING");
        display.println("Press to stop");
    } else {
        display.println("Status: IDLE");
        display.println("Press to start");
    }
    
    display.display();
}

void drawPacketStats() {
    display.clearDisplay();
    display.setTextColor(SSD1306_WHITE);
    display.setTextSize(1);
    
    // Header
    display.setCursor(0, 0);
    display.println("[PACKET STATS]");
    display.drawFastHLine(0, 10, 128, SSD1306_WHITE);
    
    display.setCursor(0, 15);
    display.println("Total: " + String(getTotalPacketCount()));
    display.println("Beacons: " + String(getPacketCount(PACKET_TYPE_BEACON)));
    display.println("Deauth: " + String(getPacketCount(PACKET_TYPE_DEAUTH)));
    display.println("Data: " + String(getPacketCount(PACKET_TYPE_DATA)));
    
    display.display();
}